apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
configMapGenerator:
  - name: products-configmap
    literals: 
    - MONGO_URI=mongodb://mongo-root-username:mongo-root-password@mongo-service.shared-services.svc.cluster.local:27017/
    - DATABASE=e-commerce
generatorOptions:
  disableNameSuffixHash: true # use a static name
bases:
- ../../../base/products