apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 32200
  - protocol: TCP
    port: 9300
    targetPort: 9300
    nodePort: 32300

