apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
configMapGenerator:
  - name: search-configmap
    literals: 
    - ELASTIC_URL=http://elastic-service.shared-services.svc.cluster.local:9200/
generatorOptions:
  disableNameSuffixHash: true # use a static name
bases:
- ../../../base/search